In [1]:
! which python

/Users/efrainolivares/envnltk/bin/python


In [2]:
from sklearn import datasets
import numpy as np

In [3]:
boston = datasets.load_boston()
print boston.DESCR

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [4]:
housing = datasets.fetch_california_housing()

In [5]:
home = datasets.get_data_home()
!echo $home # you can pass arguments to bash!
!ls $home

/Users/efrainolivares/scikit_learn_data
20news-bydate.pkz cal_housing.pkz   mldata


In [6]:
X, y = boston.data, boston.target

In [7]:
datasets.load_*?

In [8]:
reg_data = datasets.make_regression()
reg_data[0].shape

(100, 100)

In [9]:
from sklearn import preprocessing
import numpy as np

In [10]:
#use the boston set...


## Scaling data to the standard normal

In [11]:
from sklearn import preprocessing
import numpy as np

In [12]:
X[:, :3].mean(axis=0) #mean of the first 3 features

array([  3.59376071,  11.36363636,  11.13677866])

In [13]:
X[:, :3].std(axis=0)

array([  8.58828355,  23.29939569,   6.85357058])

There's actually a lot to learn from this initially. Firstly, the first feature has the smallest mean
but varies even more than the third feature. The second feature has the largest mean and
standard deviation—it takes the widest spread of values:

In [14]:
X_2 = preprocessing.scale(X[:, :3])

In [15]:
X_2.mean(axis=0)

array([  6.34099712e-17,  -6.34319123e-16,  -2.68291099e-15])

In [16]:
X_2.std(axis=0)

array([ 1.,  1.,  1.])

#  Where I left off..
* Around page 15
* did not really finish last section, but the next one seems intesting, Creating binary features through thresholding


So I think that's where we should pick up next time 